./kic email_kic.bin 0.1 2.0 sr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.2 2.0 sr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.3 2.0 sr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.4 2.0 sr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.5 2.0 sr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.6 2.0 sr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.7 2.0 sr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.8 2.0 sr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.9 2.0 sr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 1.0 2.0 sr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.1 2.0 sgr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.2 2.0 sgr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.3 2.0 sgr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.4 2.0 sgr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.5 2.0 sgr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.6 2.0 sgr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.7 2.0 sgr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.8 2.0 sgr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.9 2.0 sgr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 1.0 2.0 sgr --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.1 2.0 smw --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.2 2.0 smw --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.3 2.0 smw --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.4 2.0 smw --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.5 2.0 smw --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.6 2.0 smw --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.7 2.0 smw --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.8 2.0 smw --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.9 2.0 smw --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 1.0 2.0 smw --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.1 2.0 sm --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.2 2.0 sm --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.3 2.0 sm --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.4 2.0 sm --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.5 2.0 sm --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.6 2.0 sm --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.7 2.0 sm --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.8 2.0 sm --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 0.9 2.0 sm --nonmonotone 0 --seed 42 email_out.csv
./kic email_kic.bin 1.0 2.0 sm --nonmonotone 0 --seed 42 email_out.csv

./kic facebook_kic.bin 0.1 2.0 sr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.2 2.0 sr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.3 2.0 sr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.4 2.0 sr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.5 2.0 sr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.6 2.0 sr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.7 2.0 sr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.8 2.0 sr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.9 2.0 sr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 1.0 2.0 sr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.1 2.0 sgr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.2 2.0 sgr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.3 2.0 sgr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.4 2.0 sgr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.5 2.0 sgr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.6 2.0 sgr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.7 2.0 sgr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.8 2.0 sgr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.9 2.0 sgr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 1.0 2.0 sgr --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.1 2.0 smw --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.2 2.0 smw --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.3 2.0 smw --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.4 2.0 smw --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.5 2.0 smw --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.6 2.0 smw --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.7 2.0 smw --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.8 2.0 smw --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.9 2.0 smw --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 1.0 2.0 smw --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.1 2.0 sm --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.2 2.0 sm --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.3 2.0 sm --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.4 2.0 sm --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.5 2.0 sm --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.6 2.0 sm --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.7 2.0 sm --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.8 2.0 sm --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 0.9 2.0 sm --nonmonotone 0 --seed 42 facebook_out.csv
./kic facebook_kic.bin 1.0 2.0 sm --nonmonotone 0 --seed 42 facebook_out.csv